<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>LeetcodePlaygroundJava</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>Q2185-CountingWordsWithAGivenPrefix</module>
        <module>Q2190-MostFrequentNumberFollowingKeyInAnArray</module>
        <module>Q2194-CellsInARangeOnAnExcelSheet</module>
        <module>Q2200-FindAllK-DistantIndicesInAnArray</module>
        <module>Q2206-DivideArrayIntoEqualPairs</module>
        <module>Q2210-CountHillsAndValleysInAnArray</module>
        <module>Q2215-FindTheDifferenceOfTwoArrays</module>
        <module>Q2220-MinimumBitFlipsToConvertNumber</module>
        <module>Q2224-MinimumNumberOfOperationsToConvertTime</module>
        <module>Q2231-LargestNumberAfterDigitSwapsByParity</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>