<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>LeetcodePlaygroundJava</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>Q2185-CountingWordsWithAGivenPrefix</module>
        <module>Q2190-MostFrequentNumberFollowingKeyInAnArray</module>
        <module>Q2194-CellsInARangeOnAnExcelSheet</module>
        <module>Q2200-FindAllK-DistantIndicesInAnArray</module>
        <module>Q2206-DivideArrayIntoEqualPairs</module>
        <module>Q2210-CountHillsAndValleysInAnArray</module>
        <module>Q2215-FindTheDifferenceOfTwoArrays</module>
        <module>Q2220-MinimumBitFlipsToConvertNumber</module>
        <module>Q2224-MinimumNumberOfOperationsToConvertTime</module>
        <module>Q2231-LargestNumberAfterDigitSwapsByParity</module>
        <module>Q2235-AddTwoIntegers</module>
        <module>Q2236-RootEqualsSumOfChildren</module>
        <module>Q2239-FindClosestNumberToZero</module>
        <module>Q2243-CalculateDigitSumOfAString</module>
        <module>Q2248-IntersectionOfMultipleArrays</module>
        <module>Q2255-CountPrefixesOfAGivenString</module>
        <module>Q2259-RemoveDigitFromNumberToMaximizeResult</module>
        <module>Q2264-Largest-3-Same-DigitNumberInString</module>
        <module>Q2269-FindTheK-BeautyOfANumber</module>
        <module>Q2273-FindResultantArrayAfterRemovingAnagrams</module>
        <module>Q2278-PercentageOfLetterInString</module>
        <module>Q2283-CheckIfNumberHasEqualDigitCountAndDigitValue</module>
        <module>Q2287-RearrangeCharactersToMakeTargetString</module>
        <module>Q2293-MinMaxGame</module>
        <module>Q2299-StrongPasswordCheckerII</module>
        <module>Q2303-CalculateAmountPaidInTaxes</module>
        <module>Q2309-GreatestEnglishLetterInUpperAndLowerCase</module>
        <module>Q2315-CountAsterisks</module>
        <module>Q2319-CheckIfMatrixIsX-Matrix</module>
        <module>Q2325-DecodeTheMessage</module>
        <module>Q2331-EvaluateBooleanBinaryTree</module>
        <module>Q2335-MinimumAmountOfTimeToFillCups</module>
        <module>Q2341-MaximumNumberOfPairsInArray</module>
        <module>Q2347-BestPokerHand</module>
        <module>Q2351-FirstLetterToAppearTwice</module>
        <module>Q2357-MakeArrayZeroBySubtractingEqualAmounts</module>
        <module>Q2363-MergeSimilarItems</module>
        <module>Q2367-NumberOfArithmeticTriplets</module>
        <module>Q2373-LargestLocalValuesInAMatrix</module>
        <module>Q2379-MinimumRecolorsToGetKConsecutiveBlackBlocks</module>
        <module>Q2383-MinimumHoursOfTrainingToWinACompetition</module>
        <module>Q2389-LongestSubsequenceWithLimitedSum</module>
        <module>Q2395-FindSubarraysWithEqualSum</module>
        <module>Q2399-CheckDistancesBetweenSameLetters</module>
        <module>Q2404-MostFrequentEvenElement</module>
        <module>Q2409-CountDaysSpentTogether</module>
        <module>Q2413-SmallestEvenMultiple</module>
        <module>Q2418-SortThePeople</module>
        <module>Q2423-RemoveLetterToEqualizeFrequency</module>
        <module>Q2427-NumberOfCommonFactors</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>